name: test
# on: [push, release,workflow_dispatch]
on:
#   push:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      args:
        description: "test"
        default: "test arg"
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      TESTENV: Hello
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
        
      - name: Test Something (manually)
        if: github.event.inputs
        run: |
          ${{env.TESTENV}}="manually run"

      - name: Test Something (auto)
        if: github.event.inputs == 0
        run: |
          TESTENV="auto run"

      - name: Test Something
        run: |
          echo ${{env.TESTENV}}
          echo $TESTENV
        
